### PR TITLE
Change appeal link to forums

### PR DESCRIPTION
**Pull request by Palmidence**

### CODE REVIEW

**Comment by jellz** [comment]
I think this should stay the same, pointing to the Discord server, so it's all centralized.

**Comment by Palmidence** [comment]
But appeals aren't handled through Discord, so I'm not sure how that centralizes anything by having Discord as the message. All that happens is people join the Discord and ask where to appeal, when we could skip that step and instead give them the _actual_  link to appeal.

**Comment by danielgulic** [comment]
Well it's quite obvious that it's the #reports-appeals channel

**Comment by scorpion808** [comment]
I think it should include both the discord and the link to the forums.

**Comment by Palmidence** [comment]
@danielgulic I'd say so too, but evidently not. What's your opinion on scorpion's suggestion?

**Comment by Trophonix** [comment]
I like sending them to discord for 3 reasons:
1. They can easily fallback to the discord for help if forum posting doesn't work for some reason
2. For smaller issues, a forum post is kinda overkill and just wastes their time and the staffs' time
3. I'd like Discord to be sort of the "core" of the community. It's getting the users onto the Discord where they can see announcements and updates.

**Comment by danielgulic** [comment]
>I'd like Discord to be sort of the "core" of the community. It's getting the users onto the Discord where they can see announcements and updates

I said it should stay all centralized in the first comment @Palmidence

**Comment by Palmidence** [comment]
Then appeals should be handled through Discord.

**Pull request closed without merging**
