### PR TITLE
/report command

### PR DESCRIPTION
**Pull request by AtditC**
This is adds a relatively simple /report command to TGM.

It features:
-Report counter (reset when reconnecting)
-30 seconds cooldown (not reset when reconnecting)
-Sends report to all users who have the 'tgm.reports' permission
-If nobody with the permission is online, it returns "No online staff."

This has been tested on a test server and works fine.

### CODE REVIEW

**Comment by Draem** [comment]
To avoid troll reports, you could possibly add something similar to Hypixel, where you can only report for select reasons/hacks.

**Comment by Draem** [comment]
Also if a staff member joins it should send them the active reports (assuming the player that was reported is still online)

**Comment by JapaneseSquid** [comment]
> Also if a staff member joins it should send them the active reports (assuming the player that was reported is still online)

Reports won't have an "Open" or "closed" parameter

> To avoid troll reports, you could possibly add something similar to Hypixel, where you can only report for select reasons/hacks.

Better to just punish for troll reports than limit the reasons, I find that with Hypixel it limits how descriptive you can be. Not to mention, these reports can also be used for the chat itself, and you know how creative people can be with their messages

**Comment by Draem** [comment]
> Reports won't have an "Open" or "closed" parameter

I mean just check if the player who was reported is online and if they are then the moderator can be notified when they join.

> Better to just punish for troll reports than limit the reasons, I find that with Hypixel it limits how descriptive you can be. Not to mention, these reports can also be used for the chat itself, and you know how creative people can be with their messages

Doesn't really matter how creative their messages are, if it's disrespectful then it's disrespect, if it's discriminatory then it's discrimination, etc. Another thing that could be done is maybe add a verification before submitting to be like "Are you sure you want to submit that? If you submit a troll report you will be punished."

**Comment by JapaneseSquid** [comment]
> I mean just check if the player who was reported is online and if they are then the moderator can be notified when they join.

Atdit mentioned showing recent reports, that was in the same system he modeled his after. It's also not hard to check if players are online or not, and it's better to show all reports regardless of if they are online or not rather than showing the ones of the players who are online only

> Doesn't really matter how creative their messages are, if it's disrespectful then it's disrespect, if it's discriminatory then it's discrimination, etc. Another thing that could be done is maybe add a verification before submitting to be like "Are you sure you want to submit that? If you submit a troll report you will be punished."

Verification is not really needed, and it's a lot better to just not even spend time limiting the options since there will always be cases of exception. As for the verification, once again not needed, if they send a troll report on purpose they aren't going to stop for some verification that they won't think twice about

**Comment by Draem** [comment]
Verification would just make sure they're fully aware they will be punished (if they're just doing it to be funny and don'r realize they'll be punished), and Atdit mentioned the recent report thing after I made the comment + showing all the reports is useless since there you can't ban a hacker if they're offline. Also for restricting what they can report for could be useful as you can categorize reasons like "PVP", "Chat", etc, so staff members could specifically look at "Chat" reports since those can be verified using #server-chat.

**Comment by AtditC** [comment]
Add /reports:

This commit adds a /reports command to TGM.

Features:
-Shows all reports since server started in the same format as /maps /rot etc.
-Shows reporter and date/time of the report when you hover over a report
-Suggests /tp to the reported player when you click on a report
-Shows when he was reported in hours/minutes/seconds ago
-Disabled reporting yourself
-Changed successful return message to "Your report has been sent to online staff.", no matter if there are any staff members online.

image

image

image

**Pull request merged**
