### PR TITLE
Create better levels for Warzone

### PR DESCRIPTION
**Pull request by Sniped**
**Why should this pull request be pushed?**

This pull request should be pushed because the current Warzone levels aren't as broad as they should be and they don't have very applauding colors. Xounaut and I feel that these level colors will be a good change to the color levels. 

**What is the purpose of this pull request?**

To replace Warzone's current level colors for better color levels. 

*WARNING: THIS CODE WAS NOT TESTED* (Was too lazy to compile and test on my server, it's only if statements so should be fine)

### CODE REVIEW

**Comment by TRose2000** [comment]
"Better Levels" totally not..

1, the color order is Messy af.
2, get a better Level order,

**Comment by Sniped** [comment]
k such as?

**Comment by TRose2000** [comment]
use ur brains?

**Comment by Sniped** [comment]
I'm sorry but you're using no elaboration, use some elaboration if you want to critique my PR.

**Comment by TRose2000** [comment]
`
        else if (level < 60) { 
            return ChatColor.DARK_PURPLE + "[" + level + "]"; 
        } 
        else if (level < 80) { 
            return ChatColor.DARK_RED + "[" + level + "]"; 
        }`

From Dark Purple
you go to Dark Red?
+ ur skipping Levels, if you want more

**Comment by Sniped** [comment]
Skipping levels? Why add a color for every 10 levels?

**Comment by Sniped** [comment]
bad colors after tested out no pls close kthxbai

**Pull request closed without merging**
