### PR TITLE
FFA game type

### PR DESCRIPTION
**Pull request by jorgeberrex**

### CODE REVIEW

**Comment by jorgeberrex** [comment]
@lukechatton There's an issue with the scoreboards system that adds the score of the entry to the actual entry in some cases.

issue1 

issue2

**Comment by lukechatton** [comment]
Interesting... I'm not the author of that scoreboard utility class. I grabbed that off of the spigot forums years ago and have been using it since.

**Comment by lukechatton** [comment]
I haven't checked how you are managing the scoreboard for FFA, but I think that with that util class *everything* needs to be registered through it. You can't register/change things by raw accessing the bukkit scoreboard.

If you are registering players into the scoreboard then it's probably a sign you are doing it wrong.

**Comment by jorgeberrex** [comment]
I managed to find the SimpleScoreboard class for the scoreboard system and one of the updates it has received seems to have fixed the issue FFA was having.

**Comment by BennyDoesTheStuff** [comment]
Adds #114

**Pull request merged**
