### PR TITLE
add /website and /buy

### PR DESCRIPTION
**Pull request by DeternoMC**
Creates /website and /buy

website from #173 

credit to @Synconix i guess

### CODE REVIEW

**Comment by jorgeberrex** [comment]
In my opinion, having hard-coded links on an open source plugin is not a good idea, since it's basically forcing every server owner (that wishes to host a TGM server) to display a link for a different server's website and store, unless they change it in their fork, which is not hard to do but not ideal (once again, in my opinion). You should keep in mind that the contributions that go to this repository should be made with the objective of improving the plugin functionalities in general, not just for one specific server.
Apart from that, have you tested the commands? While I was checking the changes, I noticed that both command methods are named `next`, which in theory should not work.

**Comment by Palmidence** [comment]
The commands are Synconix's code, and no it has not been tested.

@jorgeberrex I think we can do hardcoded links and stuff like this, but only if we have a config file to link it to (so it's easy to change.)

**Comment by DeternoMC** [comment]
@jorgeberrex if that's the case, you should probably remove the no permission on joining a team message. It says something like "You cannot join this team because you aren't a donator, use autojoin instead." and so puts a link to the warzone store.

**Comment by BennyDoesTheStuff** [comment]
@DeternoMC It does have a link to the warzone store
image

**Comment by DeternoMC** [comment]
@BennyDoesTheStuff I know, I told jorge since he said we shouldn't hardcode links, that we should remove that one as well because it's hardcoded in when you're not a premium user and you try to pick your team.

**Pull request closed without merging**
