### PR TITLE
add IP to scoreboard

### PR DESCRIPTION
**Pull request by Hxnr**

### CODE REVIEW

**Comment by ThatOneTqnk** [comment]
i dont think this would compile

**Comment by Hxnr** [comment]
What is wrong with it?

**Comment by ThatOneTqnk** [comment]
`scoreboards` refers to a HashMap of UUID to SimpleScoreboard. So I think what you meant was to add a blank line to the scoreboard (`simpleScoreboard`), not add a blank line to the HashMap (`HashMap.blankLine()`)

you also may want to put those two lines before it sends it to the player and updates the hashmap

**Comment by Hxnr** [comment]
I'm highly inexperienced in Java - I made this PR as a sample for someone with a greater understanding of how Scoreboards work. Would you mind applying the fixes on my PR?

**Comment by ThatOneTqnk** [comment]
sure, ill just make a separate pr though since im not sure how i would apply the fixes to this pr

**Comment by jorgeberrex** [comment]
I know you already explained the purpose of this PR but you should probably create an issue for a feature request and mark it as high priority, providing the logic portion in a code block instead of a PR. It’s better for keeping the repository organized

**Comment by Hxnr** [comment]
#475 @jorgeberrex 

It's not high priority, though.

**Comment by jorgeberrex** [comment]
Well yeah, I was just pointing out that you could use tags for this kind of things. Either way, my point is that it’s probably best to keep completely valid suggestions like this one separate from finished (or at least close to finished) pull requests

**Pull request closed without merging**
