### PR TITLE
Added /tp, /teleport for spectators

### PR DESCRIPTION
**Pull request by Thrasilias**

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
Wouldn't work well when it comes to staff.

**Comment by JapaneseSquid** [comment]
That literally makes no sense wtf

**Comment by JapaneseSquid** [comment]
If I’m a regular and I’m tryna spec some guy am I supposed to play where’s Waldo

**Comment by Thrasilias** [comment]
i think benny still hates me like he always did.

2018-07-14 1:48 GMT+02:00 JapaneseSquid <notifications@github.com>:

**Pull request closed without merging**
