### PR TITLE
Add /ping command, fixes #184

### LINKED ISSUE #184: Add /ping
View a player's ping. Helpful when looking for hackers instead of just looking at their bars on tab.

### PR DESCRIPTION
**Pull request by RONTheCookie**

### CODE REVIEW

**Comment by MatrixTunnel** [comment]
This ping method is inaccurate and requires NMS to depend on. I recommend using reflection and using a better method of finding the player's true ping

**Comment by RONTheCookie** [comment]
I have no idea how to do that but feel free to edit this PR.

**Comment by jellz** [comment]
@RONTheCookie Clearly they want you to make the command, I think you should just close this PR ;P

**Comment by RONTheCookie** [comment]
Lucas told me he might do it a while ago but I guess I'll close it.

**Pull request closed without merging**
