### PR TITLE
Load filters when match starts

### PR DESCRIPTION
**Pull request by Draem**
Untested

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
Could you explain why you're making these changes? lol

**Comment by MatrixTunnel** [comment]
Better fix for #458

**Comment by lukechatton** [comment]
Would add some extra lag right when the match starts. But that might not be a problem here. I guess it would depend on the amount of regions setup.

Would adding a check for match status in the listener event be a better solution?

**Comment by lukechatton** [comment]
Oh that's what #458 is. I guess the less checks in a PlayerMoveEvent the better?

**Pull request merged**
