### PR TITLE
Create TeleportCommands.java

### PR DESCRIPTION
**Pull request by TRose2000**
Added teleportcommand for staff
* /rtp <player> [player]
* permission: tgm.teleport

### CODE REVIEW

**Comment by TheBestGameeer** [comment]
Staff already had access to /tp and /teleport ?

**Comment by TRose2000** [comment]
/tp has been changed since spectators can use /tp and /teleport,
/rtp = staff only

**Comment by Trophonix** [comment]
I don't get why we'd need this and I really don't like the reliance on try catch when you could easily prevent an exception

**Comment by BennyDoesTheStuff** [comment]
@Trophonix A command similar to this that would let staff members tp while they are in the game can be quite helpful. Though, I personally don't see the need on why it should be on /rtp. Could just be in /tp.

**Comment by Trophonix** [comment]
@BennyDoesTheStuff Yeah, I will just write this feature into /tp

**Pull request closed without merging**
