### PR TITLE
SpectatorModule fixes

### PR DESCRIPTION
**Pull request by TRose2000**
some spectator fixes

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
Not exactly sure why you are changing certain things. One of the reasons of the weakness is so you can't hit players in game and so others can't hear your hitting sound.

**Comment by TRose2000** [comment]
> Not exactly sure why you are changing certain things. One of the reasons of the weakness is so you can't hit players in game and so others can't hear your hitting sound.

I removed the potion effect since I made a event that deny's spectators to interact with players (damaging players / mobs)

**Comment by TRose2000** [comment]
also you cant hear spectators hitting players ingame since Spectators are fully invisible for ingame players

**Comment by TRose2000** [comment]
https://gyazo.com/6d5762298543642a054d40b6d978c03b

**Pull request closed without merging**
