### PR TITLE
Add "report" to blocked commands for muted players

### PR DESCRIPTION
**Pull request by AtditC**

### CODE REVIEW

**Comment by danielgulic** [comment]
Just because I sent one too many messages I shouldn't be allowed to report a disruptive cheater that is ruining mine and everyone else's experience on the server? I don't support this change.

**Comment by AtditC** [comment]
This has been kind of requested by Benny

**Comment by danielgulic** [comment]
Okay, and?

**Comment by AtditC** [comment]
A muted user in-game already abused the report command like two days after it was added, to contact staff members. Personally, I don't care whether it gets added or not. There are good and bad reasons.

**Comment by danielgulic** [comment]
You're advocating for a change you don't even care about?

**Comment by danielgulic** [comment]
I think it should just be against the rules to abuse the command, not block it altogether.

**Comment by AtditC** [comment]
No I don't advocate for it, but Benny wanted this so I quickly made the change. Again, there are good and bad reasons so I don't care if it gets added or not.

But how would muted people who abuse the report system get punished? The only way would be by (temporarily) banning them, as they already are muted....

**Comment by danielgulic** [comment]
They could have their mute extended, or be temp-banned. I think they should be temp-banned.

**Pull request closed without merging**
