### PR TITLE
Created Punishments

### PR DESCRIPTION
**Pull request by Thrasilias**
Added Punishment commands
 - /w <player> <reason> or /warn <player> <reason>
 - /k <player> <reason> or /kick <player> <reason>
 - /b <player> <reason> or /ban <player> <reason> (Will be added if i get help with the ban system)

### CODE REVIEW

**Comment by Arkrus** [comment]
/w is whisper. Maybe if you did /wa or /w could be replaced with something like /pm or /msg

**Comment by Thrasilias** [comment]
@Arkrus what if i change the Message System ?
so they can use /msg instead of /w ?

**Comment by Arkrus** [comment]
yeah that'll work. I said that tho

**Comment by Thrasilias** [comment]
@Arkrus im gonna work on this 1.

**Comment by BennyDoesTheStuff** [comment]
@Thrasilias The problem with that is the current /msg system is on the Minehut proxy, so that'll have to be fixed by a MH admin. And when it comes to the /w, that's a default Minecraft command.

**Comment by jorgeberrex** [comment]
A new punishment system is currently being worked on. Thank you for your contribution.

**Pull request closed without merging**
